### ISSUE TITLE
Share Price increases after redemption

### ISSUE THREAD

**Issue by GauthamN** [melonproject/protocol#383]
In tests after setting management fee to non-zero, test for share price decreasing (due to fee) or remaining constant fails in the case of redemption.

https://github.com/melonproject/protocol/blob/cbcd3357c07c525b6d7a829ffd3197ba966c3f2a/tests/integration/fundShares.js#L602

**Comment by jennazenk** [comment]
Just double checking here, but if an investor redeems his shares, _assuming constant pricefeed_, the share price should remain constant right ?

**Comment by GauthamN** [comment]
Yes unless allocateUnclaimedFees is called

**Comment by jennazenk** [comment]
but even if _allocateUnclaimedFees_ is called, it should not alter the share price imo. 

If we take this simplified example, with 50% management fees, assuming constant prices: 

At t0, fund's share price is 1. 
Investor A buys 1 share for 1 MLN. 
Investor B buys 1 share for 1 MLN. 
GAV is therefore 2 MLN.

At t1, fund has a performance of 100% (share price 2). 
GAV is now 4 MLN. 
Investor A wants to redeem his 1 share. If no fees, he would then be entitled to 2 MLN. But as stated above, there are 50% performance fees. So if he redeems one share he will only get 1 MLN. The other MLN stays in the fund, his share gets annihilated and 0.5 new share (corresponding to the management fee) is created and attributed to the fund manager.

After this payout occurred, GAV is now 3 MLN and  total # of outstanding shares is 1.5 (2 - 1 + 0.5). Share price is AUM / # outstanding shares = 2 . 

As said, this example is simplified since share price calculation should already account for fees. 

So given that example, could you explain why share price might decrease is allocateUnclaimedFees please ? would be lovely @GauthamN

**Comment by GauthamN** [comment]
I may be wrong but according to my understanding, there is no explicit reduction of fees when he redeems his shares. But the reduction comes from reduced share price. I'm not saying the share price should decrease after redemption, but rather in the test case, there is time gap between preShare price calculations and redemption, where in the meantime management fee is accumulated thereby decreasing the share price. Does this make sense?

**Comment by jennazenk** [comment]
>But the reduction comes from reduced share price.

Thats correct, that's my understanding as well. I showed it as a reduction in the example just for simplification. 

>I'm not saying the share price should decrease after redemption, but rather in the test case, there is time gap between preShare price calculations and redemption, where in the meantime management fee is accumulated thereby decreasing the share price.

Got it, makes total sense! So the share price is expected to decrease just because of management fee compounding over time during the time gap, is that correct? 

Thanks @GauthamN

**Comment by GauthamN** [comment]
Exactly :). Ideally the test case should account for this change and test for equal assertion. But this calculation of expected share price difference involves in a long series of calculations (This could be simplified if share price is stored in atLastUnclaimedFeeAllocation struct). It also leads to very small difference even with this calculation due to precision.

Anyways conceptually, it should never increase right?

**Comment by jennazenk** [comment]
Correct conceptually it should not increase ie. the redemption of an investor should not affect the share price of other investors.

**Comment by GauthamN** [comment]
Fixed it in 9c3a23240281fc730a35bcf3e11a7802ed61e1c8
