### ISSUE TITLE
divide and conquer (repo)

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#653]

**Comment by schmidsi** [comment]
Maybe do this even in a new organisation?

So far, my inputs are:

- Extract `utils` into own module, `contract-utils` that is implementation agnostic and could be used by other projects too.
- In the contract repos, there should only be Soldity-code. No JavaScript, no TypeScript. All tests (unit, integration, system, etc) should be in separate repos. This should incentivise the contract developers to write more broad and reusable tests & utils instead of tight-knit low-level tests.

**Comment by jennazenk** [comment]
- contract will be separated into different repos* (to be discussed)

**Comment by travs** [comment]
Yeah, extracting utils and the *script as you described seems fine to me.

Depending on how we implement the code sharing between repos, it might be fine to not host the thirdparty stuff, but instead just use a specific version, content-address (hash), address or similar and download it from where it is originally hosted. If we make any modifications, though, then we need to host our own. This may end up being simpler anyway, but we need to decide on that.

For other contracts in the dependencies we can follow similar logic. Specific to the dapphub contracts, we can just get them directly from their repos.

We can merge `testing` with `dependencies` yes.
The rest of the repos can be just as you described @jennazenk; each directory of `src/*` with its own repo.
