### ISSUE TITLE
Upgrading should be easier. One button solution possible?

### ISSUE THREAD

**Issue by lukue** [melonproject/protocol#801]
Hey devs,
i read about the security issues upgradeable smart contracts would bring. This is make the protocol inconvenient. 
Would it be possible to simplify the process at least? Like one button for shut-down and redeem at the same time? Or a button, where you could approve all the steps with one click in new versions to redeploy?

Also for investors some hints on the monitoring tool and the UI of the protocol, that a fund has been redeployed and a option to redeem and reinvest in the new fund in one step?

Kind regards,
lukue

**Comment by jennazenk** [comment]
Hello Lukue, we are aware that having to redeploy a fund is cumbersome but until we implement an upgradable fund feature that is the only way. Upgradable fund is something we will look into in the future, but please be aware it will be a long and complex endeavor so I'd like to manage expectations it is not to be expected in coming weeks. 

As for the interface, we've made the choice to dedicate one interface per version, in order to protect investors so that they are less likely to invest in funds that are not on the latest version. 

We are not able to do "one click shut down redeem redeploy reinvest" for the simple reason that a user needs to sign each and every transaction, ie. circa 14 transactions in that case. 

On future versions of monitoring, you will be able to see all the fund a single manager address has on different versions though. 

I'll close this as this is not an immediate issue, but will be tackled as an MIP (Melon Improvement Proposal) in the future.
