### ISSUE TITLE
Allow funds to get the pricefeed address dynamically

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#846]
Right now the address for the pricefeed is not changeable after setup.
We want it to be fetched dynamically from the registry.

**Comment by SeanJCasey** [comment]
Do we want the pricefeed address to be fetched from the Registry, or do we want fund managers to be able to call a function to update their fund's pricefeed with an approved pricefeed address in the Registry? The latter would pave the way to let fund managers choose their own pricefeed, if that's something we want.

**Comment by jennazenk** [comment]
For this issue we want for the pricefeed address to be fetched from the Registry, so that in another similar event as the kyber migration, funds created prior have access to the new pricefeed when it' changed on the rRegistry. 

The latter (fund managers choosing their own pricefeed) is not something we want to enable now (could be in the future, if there is demand for it), because comparison between funds is easier when they use the same pricefeed.
