### ISSUE TITLE
Fire events more consistently for state-changing actions

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#896]
Makes sense to do later, once functions become more stable.

- e.g. takeOrder event
- two different events with identical name in Accounting and Registry (`AssetRemoval`)

**Comment by SeanJCasey** [comment]
As discussed in our chats, we should try to improve current events as well, whether now or when it is convenient for the subgraph implementation to handle abi changes.

For example, take `ExchangeMethodCall`: https://github.com/melonproject/protocol/blob/f30009b8499d3b8b2f56bb53bc1b148c5029583f/src/fund/trading/Trading.sol#L17

Right now, this only offers the params that the `callOnExchange` function is called with, but when you think about how it should be _indexed_, the event only offers `exchangeAddress` (i.e., filter by calls to a particular exchange) or `methodSignature` (i.e., filter by `takeOrder`, etc). There is no param for which fund (i.e., `Hub` or `Trading` contract) that this action was called on, which I would think should be the primary index for filtering these events (it would certainly be the most helpful index for unit testing).

**Comment by SeanJCasey** [comment]
Another couple examples (I think this is going to be a common theme for fund events, where what we really want is a missing indexed parameter of `hub`):

https://github.com/melonproject/protocol/blob/2ac646859445b798ae85e6b3da487d6905a57020/src/fund/accounting/Accounting.sol#L15-L16

**Comment by SeanJCasey** [comment]
Actually, I can see both sides of a debate on whether it's necessary to explicitly include the `hub`. Since these events are fired from unique contract instances, it should be fine to omit who the `hub` is for web3 users who would be watching that specific contract. I just wonder about the extra convenience of having the fund address being explicit for parsing tx logs. As long as fund components are separate, you'd need to get the event's Contract address from the log and then make a call to see what the associated hub for that Contract address is.

**Comment by SeanJCasey** [comment]
Moved to CH
