### ISSUE TITLE
AmguPaid event parameters

### ISSUE THREAD

**Issue by iherger** [melonproject/protocol#915]
It would be helpful if the `AmguPaid` event parameters could include the following additional values:
- etherConsumed
- totalAmguConsumed
- totalEtherConsumed

**Comment by SeanJCasey** [comment]
Since we have 2 similar events with the same namespacing but slightly different actions/perspectives, I think it would be helpful if we named them semantically, consistently, and using consistent terminology across them. They can live side-by-side in `Engine.sol` since that is basically the authoritative contract on amgu. We can split `IncentivePaid` into its own event also, as below:

```
// Engine.sol
event AmguConsumed {
  uint256 amguTokenAmount,
  uint256 etherAmount,
  uint256 totalAmguTokenConsumed,
  uint256 totalEtherConsumed
}

event AmguFeePaid {
  address indexed payer,
  uint256 amguUnits,
  uint256 amguTokenAmount,
  uint256 etherAmount,
}

// Registry.sol, since that's where incentive is set and `IncentiveChange` is defined
event IncentivePaid {
  address indexed payer,
  address indexed payee,
  uint256 amount
}
```

**Comment by SeanJCasey** [comment]
Moved to CH
