### ISSUE TITLE
Order cancellation needs to consider partial fills

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#918]
From Adam:

My impression is that revokeApproveAssetsCancelOrder doesn't really consider that cancelled orders can be already partially filled. Which might result in attempts to reduce exchange's allowance below 0

**Comment by SeanJCasey** [comment]
Just to clarify: allowance can't go "below 0" since it's an unsigned int, plus our function uses safe math to prevent underflow, so it shouldn't be a problem.

I believe the main point is that the exchange's allowance can dip below the intended amount if there are multiple orders/allowances amalgamated into the `allowance`, in which case cancelling a partially filled order, but taking the full `makerAmount`, would eat into the allowances of the other orders.

**Comment by travs** [comment]
Fix is in c42e7e10935332ce85c076b620e5c598a2d0a485 and 95924926363cfd26cd9bf78a75197be4d1981c90
