### ISSUE TITLE
Make policies extensible

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#956]
Right now we call policy validation functions with a bunch of zero values in some cases.
Would be better if we could validate policies without having this, and also make them extensible in the sense that there is no limited interface that has to be adjusted as parameters change.

cc: @SeanJCasey 
Related to #816

**Comment by SeanJCasey** [comment]
After this is finished let's re-consider this TODO (checking policies on `requestShares`, rather than only on `executeRequestFor`): https://github.com/melonproject/protocol/blob/3184650cac8cdfcc20d4dca2521e623cf883a049/src/requests/SharesRequestor.sol#L219

**Comment by jennazenk** [comment]
@SeanJCasey on that point I was thinking shouldn't we do that check only at the execution rather than at the creation of the request? Debatable, but I feel like it should be checked in the circumstances in which the request would be executed. Debatable, I had some discussions around with this @iherger

**Comment by travs** [comment]
Policies _at minimum_ need to be checked on execute.

Is checking on request as well more or less a convenience measure? i.e. to prevent people from making impossible requests?

If so, this might actually make it more inconvenient if I want to make such a request and wait for it to become valid, then execute it. Also we could prevent these requests in a "soft" way on the frontend if we wanted to implement that check.

**Comment by jennazenk** [comment]
Yep exactly. Things like asset blacklist/whitelist could be checked at the request creation, but things that are depending on price movement or trades of the fund (max concentration / max positions) should only be checked at execution, and the prevention at creation can happen at the frontend level if we want that

**Comment by SeanJCasey** [comment]
Good points.

I was thinking of it as purely convenience. For sure, we only _need_ validation on execution (that's why it's set up like that in `SharesRequestor`). At the moment, I believe the only policy that is checked on buying shares is the user whitelist. So my thinking was that it would be bad to allow a user to pay amgu and an incentive fee to make a request to join a fund that has a whitelist that they didn't know about.

But @travs makes a good point that the frontend can actually call the `preValidate` function on the policy manager directly.

**Comment by SeanJCasey** [comment]
Moved to GH
