### ISSUE TITLE
updateKyber necessary

### ISSUE THREAD

**Issue by iemwill** [melonproject/protocol#978]
Hei Team! The owner of 0x00360d2b7D240Ec0643B6D819ba81A09e40E5bCd should update the PriceFeed on `kovan-kyberPrice.json`. It is down and i dont see a way me updating it, right?

Are there other maintained networks?

cheers

**Comment by travs** [comment]
Hi @iemwill , it's best to reach out to us via keybase as before for this type of issue, since it is not a bug in the software. Also, that address has not been used to update the kovan pricefeed for some time. I have confirmed that the kovan feed updater is running for the latest version, so please ping us on keybase with the address of the feed you are using, and we can give you some guidance.

**Comment by iemwill** [comment]
meant this one https://github.com/melonproject/protocol/blob/develop/deployments/configs/kovan-kyberPrice/022-postv1.json
found someone with updater permission and updated myself, next time keybase for such not code relevant topics.
